version: "3.8"
services:
  php:
    container_name: php
    build: ./docker/php-fpm
    networks:
      - php-framework-tuto
    volumes:
      - ./app:/var/www
  nginx:
    container_name: nginx
    image: nginx:1.19
    ports:
      - 80:80
    networks:
      - php-framework-tuto
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
networks:
  php-framework-tuto:

